services:
    symfony_cmf_multilang_content.node_translation:
        class: Symfony\Cmf\Bundle\MultilangContentBundle\Translation\SimpleNodeTranslator
        arguments:
            container: "@service_container"
            document_manager: "@doctrine_phpcr.odm.default_document_manager"
            session: @doctrine_phpcr.default_session
            annotation_reader: @symfony_cmf_multilang_content.annotation_reader
            lang_prefix: %symfony_cmf_multilang_content.lang_prefix%

    symfony_cmf_multilang_content.chooser:
        class: Symfony\Cmf\Bundle\MultilangContentBundle\Translation\LanguageChooser
        arguments:
            container: "@service_container"
            available_langs: %symfony_cmf_multilang_content.lang_preference%
            default_lang: %symfony_cmf_multilang_content.default_lang%
            lang_meta: %symfony_cmf_multilang_content.lang_meta%

    symfony_cmf_multilang_content.annotation_reader:
        class: Symfony\Cmf\Bundle\MultilangContentBundle\Annotation\Reader

    symfony_cmf_multilang_content.event_listener:
        class: %symfony_cmf_multilang_content.event_listener_class%
        arguments:
            session: @doctrine_phpcr.default_session
            annotation_reader: @symfony_cmf_multilang_content.annotation_reader
            lang_helper: @symfony_cmf_multilang_content.chooser
            lang_prefix: %symfony_cmf_multilang_content.lang_prefix%
        tags:
            - { name: doctrine_phpcr.event_subscriber }

    symfony_cmf_multilang_content.languageSelectorController:
        class: Symfony\Cmf\Bundle\MultilangContentBundle\Controller\LanguageSelectorController
        arguments:
            container: "@service_container"
            session: "@doctrine_phpcr.default_session"
            chooser: "@symfony_cmf_multilang_content.chooser"
            routename: "%symfony_cmf_navigation.mainmenu_routename%"
